package com.onlinehelpdesk.entities;
// Generated Oct 31, 2023, 11:57:37 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;


/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name = "nhanvien")
public class Nhanvien implements java.io.Serializable {

	private String username;
	private String password;
	private String hoten;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date ngaysinh;
	private Boolean kichhoat;
	private String hinhanh;
	private Integer quyen;
	private Set<Yeucau> yeucausForNvXuly = new HashSet<>(0);
	private Set<Yeucau> yeucausForNvGui = new HashSet<>(0);

	public Nhanvien() {
	}

	public Nhanvien(String username) {
		this.username = username;
	}

	public Nhanvien(String username, String password, String hoten, Date ngaysinh, Boolean kichhoat, String hinhanh,
			Integer quyen, Set<Yeucau> yeucausForNvXuly, Set<Yeucau> yeucausForNvGui) {
		this.username = username;
		this.password = password;
		this.hoten = hoten;
		this.ngaysinh = ngaysinh;
		this.kichhoat = kichhoat;
		this.hinhanh = hinhanh;
		this.quyen = quyen;
		this.yeucausForNvXuly = yeucausForNvXuly;
		this.yeucausForNvGui = yeucausForNvGui;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "hoten")
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaysinh", length = 10)
	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@Column(name = "kichhoat")
	public Boolean getKichhoat() {
		return this.kichhoat;
	}

	public void setKichhoat(Boolean kichhoat) {
		this.kichhoat = kichhoat;
	}

	@Column(name = "hinhanh")
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@Column(name = "quyen")
	public Integer getQuyen() {
		return this.quyen;
	}

	public void setQuyen(Integer quyen) {
		this.quyen = quyen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvienByNvXuly")
	public Set<Yeucau> getYeucausForNvXuly() {
		return this.yeucausForNvXuly;
	}

	public void setYeucausForNvXuly(Set<Yeucau> yeucausForNvXuly) {
		this.yeucausForNvXuly = yeucausForNvXuly;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvienByNvGui")
	public Set<Yeucau> getYeucausForNvGui() {
		return this.yeucausForNvGui;
	}

	public void setYeucausForNvGui(Set<Yeucau> yeucausForNvGui) {
		this.yeucausForNvGui = yeucausForNvGui;
	}

}
