package com.onlinehelpdesk.entities;
// Generated Oct 31, 2023, 11:57:37 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Yeucau generated by hbm2java
 */
@Entity
@Table(name = "yeucau")
public class Yeucau implements java.io.Serializable {

	private int mayeucau;
	private Douutien douutien;
	private Nhanvien nhanvienByNvXuly;
	private Nhanvien nhanvienByNvGui;
	private String tieude;
	private String noidung;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date ngaygui;

	public Yeucau() {
	}

	public Yeucau(int mayeucau) {
		this.mayeucau = mayeucau;
	}

	public Yeucau(int mayeucau, Douutien douutien, Nhanvien nhanvienByNvXuly, Nhanvien nhanvienByNvGui, String tieude,
			String noidung, Date ngaygui) {
		this.mayeucau = mayeucau;
		this.douutien = douutien;
		this.nhanvienByNvXuly = nhanvienByNvXuly;
		this.nhanvienByNvGui = nhanvienByNvGui;
		this.tieude = tieude;
		this.noidung = noidung;
		this.ngaygui = ngaygui;
	}

	@Id

	@Column(name = "mayeucau", unique = true, nullable = false)
	public int getMayeucau() {
		return this.mayeucau;
	}

	public void setMayeucau(int mayeucau) {
		this.mayeucau = mayeucau;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "madouutien")
	public Douutien getDouutien() {
		return this.douutien;
	}

	public void setDouutien(Douutien douutien) {
		this.douutien = douutien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nv_xuly")
	public Nhanvien getNhanvienByNvXuly() {
		return this.nhanvienByNvXuly;
	}

	public void setNhanvienByNvXuly(Nhanvien nhanvienByNvXuly) {
		this.nhanvienByNvXuly = nhanvienByNvXuly;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nv_gui")
	public Nhanvien getNhanvienByNvGui() {
		return this.nhanvienByNvGui;
	}

	public void setNhanvienByNvGui(Nhanvien nhanvienByNvGui) {
		this.nhanvienByNvGui = nhanvienByNvGui;
	}

	@Column(name = "tieude")
	public String getTieude() {
		return this.tieude;
	}

	public void setTieude(String tieude) {
		this.tieude = tieude;
	}

	@Column(name = "noidung", length = 65535)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaygui", length = 10)
	public Date getNgaygui() {
		return this.ngaygui;
	}

	public void setNgaygui(Date ngaygui) {
		this.ngaygui = ngaygui;
	}

}
